### ISSUE TITLE
HPlayerEye.GetAngles() always returns vector : (0.000000, 0.000000, 0.000000)

### ISSUE THREAD

**Issue by eren-erver** [samisalreadytaken/vs_library#1]
I wasn't sure if this was a library bug or a coding mistake so I am posting it here.
The problem is when I execute StartTimer function. Console just prints vector : (0.000000, 0.000000, 0.000000)

```
IncludeScript("vs_library")

function StartTimer() {
	
	VS.Timer(false, 0.5 , Think)
	
	
    
}
function Think()
{
	HPlayer <- VS.GetLocalPlayer()
	HPlayerEye <- VS.CreateMeasure(HPlayer.GetName())
	printl(HPlayerEye.GetAngles())



	
}
```

Here are some screenshots of the event listeners:
![event_listener-1](https://user-images.githubusercontent.com/56906741/98355879-d0986000-2033-11eb-8ae4-28a01fe2113d.png)
![event_listener-2](https://user-images.githubusercontent.com/56906741/98355883-d1c98d00-2033-11eb-8407-445ff3d80668.png)

**Comment by samisalreadytaken** [comment]
Event listeners are irrelevant to angle measuring.

It's important to understand when to do what. Your code creates a new measure entity on each Think, and prints the freshly created entity's angles. Starting to measure is asynchronous, it needs 1 frame to start measuring.

You'll want to create the required entities first, then use another function to start all - asynchronous from the creation.

Checking if the entities were already created is also important to make sure duplicate entities are not created.

Where, when and how to call these functions depends on your map.

```cs
function InitEntities()
{
	if ( "hTimer" in this || hTimer )
		return

	hTimer <- VS.Timer( true, 0.5, Think ).weakref()
	HPlayer <- VS.GetLocalPlayer().weakref()
	HPlayerEye <- VS.CreateMeasure("").weakref()
}

function StartTimer()
{
	VS.SetMeasure( HPlayerEye, HPlayer.GetName() )
	// VS.OnTimer( hTimer, Think ) // can be used to change what function is called
	EntFireByHandle( hTimer, "Enable" )
}

function Think()
{
	printl( HPlayerEye.GetAngles() )
}
```
