### ISSUE TITLE
VS::CreateEntity is incompatible with prop entities

### ISSUE THREAD

**Issue by VulcanShot** [samisalreadytaken/vs_library#12]
`Entities.CreateByClassname()` does not work properly when trying to spawn prop entities. In these cases `CreateProp()` should be used instead. Since `VS.CreateEntity()` always calls the former, it is not usable when trying to spawn a prop.

I suggest creating a method (`VS.CreateProp()`?) for this matter, and possible throwing an exception when `VS.CreateEntity()` is called with a prop classname.

On the other hand, the same function could handle both cases. However, it must be noted that `CreateProp()`'s signature forces a model and an animation to be passed.

**Comment by samisalreadytaken** [comment]
`VS.CreateEntity()` is a stupid simple wrapper to simplify typing `__KeyValueFrom` multiple times, I don't think it should include special cases for props.

Though I don't see why creating non-animated props wouldn't work with `CreateEntity`. As you can [see here](https://github.com/jonathonracz/alienswarm-sdk-src/blob/master/game/server/vscript_server.cpp#L313-L328), `CreateProp` is identical to the following vscript code
```cs
local ent = Entities.CreateByClassname()
ent.SetAbsOrigin()
ent.SetModel()
// SetPlaybackRate(1)
// SetSequence(  SelectWeightedSequence() )
```

**Comment by VulcanShot** [comment]
Agreed.

As for the other topic, it seems like `Entities.CreateByClassname()` causes problems with prop animations. They seem to get stuck at a random frame regardless of the keyframes `playbackrate`, `sequence`, and `DefaultAnim` being set to appropriate values. Really weird.

**Comment by samisalreadytaken** [comment]
Use `SetAnimation` and `SetPlaybackRate` inputs instead of setting keyvalues.

```cs
PrecacheModel( "models/player/custom_player/legacy/tm_phoenix_varianta.mdl" )

local p = Entities.CreateByClassname("prop_dynamic")
p.SetAbsOrigin( player.GetOrigin() + player.GetForwardVector() * 32 )
p.SetModel( "models/player/custom_player/legacy/tm_phoenix_varianta.mdl" )
p.__KeyValueFromInt( "solid", 2 )
p.__KeyValueFromString( "defaultanim", "rom" )
EntFireByHandle( p, "SetAnimation", "rom" )
EntFireByHandle( p, "SetPlaybackRate", 0.25 )
```
