### ISSUE TITLE
StopTimer like SourceMod

### ISSUE THREAD

**Issue by laper32** [samisalreadytaken/vs_library#3]
Hello, there is a problem what I'm wondering.

It is hard to describe, so that I will use example to describe it.

For example, in an instance, counting: 
When the counter reaches a limit, then stops counting, and release the counter handle, from the memory.

I've found the whole library, but didn't found how to do it...

In other languages, for example, sourcepawn, can be done like this, what is shown below:
```csharp
int counter = 0;
Handle hTimer = null;
public void OnPluginStart()
{
    delete hTimer;
    hTimer = CreateTimer(1.0, Func, _, TIMER_REPEAT | TIMER_FLAG_NO_MAPCHANGE);
}

public Action Func(Handle myself)
{
    counter++
    if (counter >= 5)
    {
        counter = 0;
        hTimer = null;
        return Plugin_Stop; // Here to stop the timer
    }
    return Plugin_Continue;
}
```

Is there any method/tutorial to reach this problem in VScript? thx

**Comment by samisalreadytaken** [comment]
A `logic_timer` entity is used in vscript to create timers.  There are some utility functions in vs_library for this, although you don't necessarily need to use them.

```cpp
CTimerEntity VS::CreateTimer(bool bDisabled, float flInterval, float flLower = null, float flUpper = null, bool bOscillator = false, bool bMakePersistent = false);
table VS::OnTimer(CTimerEntity ent, closure func, table env = null);
```

How you'll write the script depends on which entity you're running it on - whether is respawned every round (e.g. logic_script) or not (e.g. info_target). The simplest way is using one that does not respawn so you don't have to think about resetting variables. If you need callbacks on post entity spawn, you can always use a different logic_script entity for that.

Rewriting your snippet and executing it in an info_target would be:

```cs
IncludeScript("vs_library");

counter <- 0;
hTimer <- null;

function Func()
{
	counter++;
	if (counter >= 5)
	{
		counter = 0;
		hTimer.Destroy();
		hTimer = null;
	}
}

hTimer = VS.CreateTimer( 0, 1.0 );
VS.OnTimer( hTimer, Func, this );
```

Controlling the state of the timer is done by firing inputs (`CBaseEntity::AcceptInput`). This is done with `EntFire`/`EntFireByHandle` in vscript.

```cpp
EntFireByHandle( hTimer, "Enable" );
```

However I do not suggest killing entities unless you are absolutely done with them until the end of the map because there are string leaks in vscript. You can instead make the timers persistent so that they are not removed at round end, and toggle them.

```cs
IncludeScript("vs_library");

counter <- 0;
hTimer <- null;

function Func()
{
	counter++;
	if (counter >= 5)
	{
		counter = 0;
		EntFireByHandle( hTimer, "Disable" );
		return;
	}
}

hTimer = VS.CreateTimer( 1, 1.0 ); // start disabled
VS.MakePersistent( hTimer );
VS.OnTimer( hTimer, Func, this );

// global function to test easily with console command `script EnableTimer()`
::EnableTimer <- function()
{
	counter = 0;
	EntFireByHandle( hTimer, "Enable" );
}.bindenv(this)
```

In vscript there is no data persistence across map changes, and scripts attached to entities are executed on every entity spawn.

**Comment by laper32** [comment]
> A `logic_timer` entity is used in vscript to create timers. There are some utility functions in vs_library for this, although you don't necessarily need to use them.
> 
> ```c++
> CTimerEntity VS::CreateTimer(bool bDisabled, float flInterval, float flLower = null, float flUpper = null, bool bOscillator = false, bool bMakePersistent = false);
> table VS::OnTimer(CTimerEntity ent, closure func, table env = null);
> ```
> 
> How you'll write the script depends on which entity you're running it on - whether is respawned every round (e.g. logic_script) or not (e.g. info_target). The simplest way is using one that does not respawn so you don't have to think about resetting variables. If you need callbacks on post entity spawn, you can always use a different logic_script entity for that.
> 
> Rewriting your snippet and executing it in an info_target would be:
> 
> ```cs
> IncludeScript("vs_library");
> 
> counter <- 0;
> hTimer <- null;
> 
> function Func()
> {
> 	counter++;
> 	if (counter >= 5)
> 	{
> 		counter = 0;
> 		hTimer.Destroy();
> 		hTimer = null;
> 	}
> }
> 
> hTimer = VS.CreateTimer( 0, 1.0 );
> VS.OnTimer( hTimer, Func, this );
> ```
> 
> Controlling the state of the timer is done by firing inputs (`CBaseEntity::AcceptInput`). This is done with `EntFire`/`EntFireByHandle` in vscript.
> 
> ```c++
> EntFireByHandle( hTimer, "Enable" );
> ```
> 
> However I do not suggest killing entities unless you are absolutely done with them until the end of the map because there are string leaks in vscript. You can instead make the timers persistent so that they are not removed at round end, and toggle them.
> 
> ```cs
> IncludeScript("vs_library");
> 
> counter <- 0;
> hTimer <- null;
> 
> function Func()
> {
> 	counter++;
> 	if (counter >= 5)
> 	{
> 		counter = 0;
> 		EntFireByHandle( hTimer, "Disable" );
> 		return;
> 	}
> }
> 
> hTimer = VS.CreateTimer( 1, 1.0 ); // start disabled
> VS.MakePersistent( hTimer );
> VS.OnTimer( hTimer, Func, this );
> 
> // global function to test easily with console command `script EnableTimer()`
> ::EnableTimer <- function()
> {
> 	counter = 0;
> 	EntFireByHandle( hTimer, "Enable" );
> }.bindenv(this)
> ```
> 
> In vscript there is no data persistence across map changes, and scripts attached to entities are executed on every entity spawn.

Thanks
NOTE: This issue, I want to keep it as open, for people who want to make a reference.

**Comment by samisalreadytaken** [comment]
Feel free to share this around, but as far as this issue goes, it is resolved; I'll close it.
