### ISSUE TITLE
Is it effective that use the following vscript code to set up an logic_eventlistener and point_template entity, so that the vs_events.nut can work?

### ISSUE THREAD

**Issue by YzGLBigTiger** [samisalreadytaken/vs_library#6]
if ( !("eventlistener" in getroottable()) || !( getroottable()["eventlistener"].IsValid()) ) 
{
	::eventlistener <- Entities.CreateByClassname("logic_eventlistener");
	::eventlistener.__KeyValueFromString("targetname","vs.eventlistener");
}

if ( !("pointtemplate" in getroottable()) || !( getroottable()["pointtemplate"].IsValid()) ) 
{
	::pointtemplate <- Entities.CreateByClassname("point_template");
	::pointtemplate.__KeyValueFromString("vscripts","vs_events.nut");
	::pointtemplate.__KeyValueFromString("Template01","vs.eventlistener");
}

IncludeScript("vs_events");

**Comment by samisalreadytaken** [comment]
No, that is not possible. I would have already done it if it was, and I will do it if it ever becomes possible.

**Comment by YzGLBigTiger** [comment]
thanks a lot
